### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL

### ISSUE THREAD

**Issue by ryanboyd** [ietz/nytimes-scraper#1]
When running from the command line:

`python -m nytimes_scraper [api-key]`

It appears to throw an error once it reaches 2019-10:

```
Fetching articles for 2019-10
  1%|▌                                                                                                    | 45/7580 [00:20<56:46,  2.21Article/s]Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\lib\site-packages\nytimes_scraper\__main__.py", line 6, in <module>
    fire.Fire(run_scraper)
  File "C:\Python36\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Python36\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\Python36\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Python36\lib\site-packages\nytimes_scraper\scraper.py", line 21, in run_scraper
    scrape_month(api_key, date)
  File "C:\Python36\lib\site-packages\nytimes_scraper\scraper.py", line 36, in scrape_month
    store=store,
  File "C:\Python36\lib\site-packages\nytimes_scraper\scraper.py", line 52, in cached
    df = fetch()
  File "C:\Python36\lib\site-packages\nytimes_scraper\scraper.py", line 33, in <lambda>
    fetch=lambda: articles_to_df(fetch_articles_by_month(api, date)),
  File "C:\Python36\lib\site-packages\nytimes_scraper\articles\scraper.py", line 18, in fetch_articles_by_month
    article['html'] = fetch_article_html(article['web_url'])
  File "C:\Python36\lib\site-packages\nytimes_scraper\articles\scraper.py", line 25, in fetch_article_html
    return requests.get(article_url).text
  File "C:\Python36\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python36\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Python36\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

**Comment by ietz** [comment]
Sorry about that. I have just published version 1.1.1 on pypi which should fix this. Feel free to reopen or create another issue if you have any other problems.
